; ESTE PROGRAMA AL PARECER ESTA LISTO, RECIBE MENSAJES ESTANDAR Y LOS
; ALMACENA LISTO.

TI      EQU 99H
BAND 	EQU 50H
RI   	EQU 98H
PDIS 	EQU 9CH
STRDIS  EQU 0A5H
DDIS 	EQU 99H
KEY 	EQU 90H

   MOV  A,#01H
   LCALL PDIS
   MOV  TMOD,#20H
   MOV TL1,#0FDH
   MOV TH1,#0FDH
   MOV IE,#90H
   MOV TCON,#40H
   MOV  SCON,#50H
   MOV  BAND,#01H

FHUI SJMP  FHUI

PROCEDA MOV  R0,#51H
 	MOV A,@R0
 	CJNE A,#0F0H,BLOQ
  	MOV A,#01H
 	LCALL PDIS
	MOV  R0,#3AH
	LCALL	DISRAM
; 	MOV  DPTR,#COL
; 	LCALL  STRDIS
 	POP 00
 	SJMP FHUI
BLOQ    CJNE  A,#0F6H,MARER
 	MOV  A,#01H
 	LCALL PDIS
 	MOV DPTR,#CBLO
   	LCALL STRDIS
  	POP 00
 	SJMP  FHUI
MARER   CJNE  A,#0F7H,COMER 
 	MOV  A,#01H
 	LCALL PDIS
 	MOV DPTR,#DERR
   	LCALL STRDIS
  	POP 00
 	SJMP  FHUI
COMER   CJNE  A,#0F8H,NOCOLG
 	MOV  A,#01H
 	LCALL PDIS
 	MOV DPTR,#CERR
   	LCALL STRDIS
  	POP 00
 	SJMP  FHUI

NOCOLG  CJNE  A,#0F1H,NODESC
 	MOV  A,#01H
 	LCALL PDIS
 	MOV DPTR,#DESC
   	LCALL STRDIS
  	POP 00
 	SJMP  FHUI
NODESC  CJNE A,#0F2H,NOMARC
   	MOV A,#01H
 	LCALL PDIS
 	MOV  DPTR,#MARC
  	LCALL STRDIS
 	MOV A,#0C0H
  	LCALL PDIS
 	MOV A,#20H
 	LCALL  DDIS
 	LCALL DISRAM 
  	POP  00H
  	SJMP FHUI
NOMARC  CJNE A,#0F3H,MENSAS
 	MOV A,#01H
 	LCALL PDIS
 	MOV DPTR,#COMU
 	LCALL STRDIS
  	MOV A,#0C0H
  	LCALL  PDIS
 	MOV DPTR,#TIEM
 	LCALL STRDIS
  	LCALL DISRAM
 	MOV DPTR,#VALO
 	LCALL STRDIS
 	LCALL DISRAM
  	POP  00
  	AJMP FHUI

DISRAM  INC R0
 	MOV A,@R0
 	CJNE A,#0FEH,NOPU
  	RET
NOPU    LCALL DDIS
   	SJMP DISRAM

MENSAS  CJNE A,#0FDH,NOCOMU
        MOV  R1,#3AH
LOOP2	 ;INC	R0
	 MOV	A,@R0
	 MOV	@R1,A
	 INC	R1
	INC R0
	 CJNE	A,#0FEH,LOOP2
	 MOV    @R1,#0FEH
         POP  00H
TIRI     AJMP FHUI

NOCOMU  CJNE A,#0F4H,TIRI
 	MOV A,#01H
  	LCALL PDIS
  	MOV DPTR,#INTERNAL
 	LCALL  STRDIS
 	POP 00
 	LJMP FHUI

	ORG 9300H

INTER   CLR  RI
	MOV  A,BAND
 	CJNE A,#01H,NOESPRIM
  	MOV  A,SBUF
  	CJNE  A,#02H,NONON
TRESI  	MOV  BAND,#02H
  	PUSH 00
 	MOV R0,#51H
SALTA   MOV  SP,#2AH
 	MOV  2AH,#93H
        MOV 29H,#23H
  	RETI

NOESPRIM  MOV A,SBUF
    	  MOV @R0,A
;   	  LCALL  DDIS
  	  INC R0
  	  SJMP SALTA
CHA  	CJNE A,#0FFH,CHA
	MOV BAND,#01H
    	LJMP PROCEDA

NONON  	CJNE	A,#21H,GUIA
	SJMP   TRESI
GUIA    RETI

COL  	DB 'COLGADO ',00H
DESC 	DB  'DESCOLGADO ',00H
MARC  	DB 'MARCANDO ',00H
COMU 	DB 'COMUNICACION ',00H
INTERNAL  DB 'INTERNACIONAL',00H
TIEM  	DB  'T : ',00H
VALO  	DB '$ ',00H
CERR    DB 'COM. ERROR',00H
DERR    DB 'MARC. ERROR',00H
CBLO	DB 'CAB. BLOQUEADA',00H

	ORG 9FFCH
	LJMP INTER
  END

