#ifndef __HB_IDS_H
#define __HB_IDS_H

const UI_HELP_CONTEXT HB_ENTER_BOOTH         = 0x0200;
const UI_HELP_CONTEXT HB_ENTER_TEL           = 0x0201;
const UI_HELP_CONTEXT HB_ENTER_TAR           = 0x0202;
const UI_HELP_CONTEXT HB_ENTER_IAMOUNT       = 0x0203;
const UI_HELP_CONTEXT HB_ENTER_DAMOUNT       = 0x0204;
const UI_HELP_CONTEXT HB_ENTER_CITY          = 0x0205;
const UI_HELP_CONTEXT HB_ENTER_COUNTRY       = 0x0206;
const UI_HELP_CONTEXT HB_ENTER_TIME          = 0x0207;
const UI_HELP_CONTEXT HB_ENTER_DATE          = 0x0208;
const UI_HELP_CONTEXT HB_ENTER_ETIME         = 0x0209;
const UI_HELP_CONTEXT HB_ENTER_VALUE         = 0x020A;
const UI_HELP_CONTEXT HB_ENTER_WORDS         = 0x020B;
const UI_HELP_CONTEXT HB_ENTER_MOTIF         = 0x020C;
const UI_HELP_CONTEXT HB_ENTER_UV            = 0x020D;
//
const UI_HELP_CONTEXT HB_80_FORM    				 = 0x020E;
const UI_HELP_CONTEXT HB_40_FORM    				 = 0x020F;
const UI_HELP_CONTEXT HB_18_FORM						 = 0x0210;
const UI_HELP_CONTEXT HB_28_FORM						 = 0x0211;
//
#endif // __HB_IDS_H
