#ifdef USE_HELP_CONTEXTS
const UI_HELP_CONTEXT H_ABOUT                          = 0x0001; // Acerca de SmartTar
const UI_HELP_CONTEXT H_ACCUM                          = 0x0002; // Acumulados
const UI_HELP_CONTEXT H_ADM_REC                        = 0x0003; // Administración de recibos
const UI_HELP_CONTEXT H_ALARM                          = 0x0004; // Programación de Alarmas del Sistema
const UI_HELP_CONTEXT H_ALIAS                          = 0x0005; // Identificadores de las Cabinas
const UI_HELP_CONTEXT H_CALC                           = 0x0006; // Calculadora
const UI_HELP_CONTEXT H_CASH                           = 0x0007; // Apertura de la caja
const UI_HELP_CONTEXT H_CHANGE_PASSWD                  = 0x0008; // Cambio de Código de Acceso
const UI_HELP_CONTEXT H_CONFIG_MENU                    = 0x0009; // Menú Configuración del Sistema
const UI_HELP_CONTEXT H_FILE_MENU                      = 0x000A; // Menú Administración de archivos
const UI_HELP_CONTEXT H_FOOTER                         = 0x000B; // Mensaje de Fin de Recibo
const UI_HELP_CONTEXT H_FORMS                          = 0x000C; // Formatos de Impresión
const UI_HELP_CONTEXT H_GENERAL                        = 0x000D; // Ayuda General
const UI_HELP_CONTEXT H_HELP_MENU                      = 0x000E; // Menú de Ayudas del Sistema
const UI_HELP_CONTEXT H_INFO_MENU                      = 0x000F; // Menú de Configuración del Sistema
const UI_HELP_CONTEXT H_INSTALL                        = 0x0010; // Instalación de SmartTar
const UI_HELP_CONTEXT H_INTER                          = 0x0011; // Internacional
const UI_HELP_CONTEXT H_INTER_TAR                      = 0x0012; // Tarifas Internacionales
const UI_HELP_CONTEXT H_IPRINT                         = 0x0013; // Impresión Internacional
const UI_HELP_CONTEXT H_LOCK                           = 0x0014; // Bloqueo/Desbloqueo
const UI_HELP_CONTEXT H_LOCK_NUM                       = 0x0015; // Bloqueo de Numeración
const UI_HELP_CONTEXT H_MANUAL                         = 0x0016; // Servicio de Impresión de Recibos Manual
const UI_HELP_CONTEXT H_MD                             = 0x0017; // Acerca de MicroDiseño Ltda.
const UI_HELP_CONTEXT H_NAL_TAR                        = 0x0018; // Tarifas Nacionales
const UI_HELP_CONTEXT H_NEW_CITY                       = 0x0019; // Nuevas Localidades Nacionales
const UI_HELP_CONTEXT H_NEW_COUNTRY                    = 0x001A; // Nuevos Países
const UI_HELP_CONTEXT H_OP_ID                          = 0x001B; // Identificación del Operario
const UI_HELP_CONTEXT H_OPERATION                      = 0x001C; // Operación de Impresión de recibos
const UI_HELP_CONTEXT H_P_PORT                         = 0x001D; // Puerto Paralelo
const UI_HELP_CONTEXT H_PASSWORD                       = 0x001E; // Activar Menú de Configuración.
const UI_HELP_CONTEXT H_PPORT                          = 0x001F; // Puerto de Impresora
const UI_HELP_CONTEXT H_PRINT_MENU                     = 0x0020; // Menú de Impresión del Sistema
const UI_HELP_CONTEXT H_QUIT                           = 0x0021; // Salir de SmartTar
const UI_HELP_CONTEXT H_RECEIPT                        = 0x0022; // Impresión de Recibos
const UI_HELP_CONTEXT H_ROUND                          = 0x0023; // Redondeo del Valor de la Factura
const UI_HELP_CONTEXT H_S_PORT                         = 0x0024; // Puerto Serie
const UI_HELP_CONTEXT H_SACCUM                         = 0x0025; // Acumulados especiales
const UI_HELP_CONTEXT H_SDAYS                          = 0x0026; // Días Festivos
const UI_HELP_CONTEXT H_SETUP                          = 0x0027; // Configuración de SmartTar
const UI_HELP_CONTEXT H_SIGNAL                         = 0x0028; // Señal de Contestación
const UI_HELP_CONTEXT H_SIMULA                         = 0x0029; // Simulación de Llamadas
const UI_HELP_CONTEXT H_SP_SERV                        = 0x002A; // Servicios Especiales
const UI_HELP_CONTEXT H_SPY                            = 0x002B; // Intervenir Cabina
const UI_HELP_CONTEXT H_SYS_INFO                       = 0x002C; // Configuración General del Sistema
const UI_HELP_CONTEXT H_TIME_DATE                      = 0x002D; // Hora y Fecha
const UI_HELP_CONTEXT H_TIMES                          = 0x002E; // Tiempos de Operación
const UI_HELP_CONTEXT H_VIEWER                         = 0x002F; // Visualizador de Recibos
const UI_HELP_CONTEXT H_ZPRINT                         = 0x0030; // Impresión Zonal
#endif // USE_HELP_CONTEXTS

