

#ifdef USE_PHONE_BOOK
const USHORT NAME_PROMPT                      = 0x0001;
const USHORT NAME                             = 0x0003;
const USHORT ADDRESS_PROMPT                   = 0x0019;
const USHORT ADDRESS                          = 0x002C;
const USHORT WORK_PHONE_PROMPT                = 0x001A;
const USHORT WORK_PHONE                       = 0x0004;
const USHORT HOME_PHONE_PROMPT                = 0x001B;
const USHORT HOME_PHONE                       = 0x0005;
const USHORT FIND_BUTTON                      = 0x0007;
const USHORT SAVE_BUTTON                      = 0x0008;
const USHORT DELETE_BUTTON                    = 0x0009;
#endif // USE_PHONE_BOOK

