/*= Archive Library v2.12 ================================================
 |  Copyright (c) 1994-1997, Greenleaf Software, Inc.
 |  All Rights Reserved.
 |
 +- Description ----------------------------------------------------------
 |  Header file.
 |
 +========================================================================*/

#define AL_STATUS	         108
#define AL_ARCHIVE      	  110
#define AL_BYTE_COUNT	     112
#define AL_OPERATION	      113
#define AL_ABORT	          101
#define AL_COMPRESS	       100
#define AL_ICON            200
#define AL_MAIN_DIALOG     201
#define AL_ABOUT        	  102
#define AL_EXIT         	  103
#define AL_ABOUT_DIALOG    204
#define AL_TEXT            205
#define AL_FILES	          111
