/*= Archive Library v2.12 ================================================
 |  Copyright (c) 1994-1997, Greenleaf Software, Inc.
 |  All Rights Reserved.
 |
 +- Description ----------------------------------------------------------
 |  Header file.
 |
 +========================================================================*/

#define IDC_STATIC	            113
#define AL_PROGRESS_TEXT	      109
#define AL_PROGRESS_BAR	       110
#define AL_ARCHIVE_CONTENTS   	102
#define AL_INPUT_FILES	        101
#define AL_DIR_MASK	           106
#define AL_ARCHIVE_NAME	       107
#define AL_ABOUT	              108
#define AL_ABOUT_TEXT	         201
#define AL_APPEND	             103
#define AL_ABORT	              104
#define AL_EXIT	               105
#define AL_DEF                 150
#define AL_ICON	               300
#define AL_MAIN_DIALOG	        100
#define AL_ABOUT_DIALOG	       200
#define AL_TEXT	               205
