/*= Archive Library v2.12 ================================================
 |  Copyright (c) 1994-1997, Greenleaf Software, Inc.
 |  All Rights Reserved.
 |
 +- Description ----------------------------------------------------------
 |  Header file.
 |
 +========================================================================*/

#define AL_PROGRESS_BAR         100
#define AL_ARCHIVE_CONTENTS     101
#define AL_READ_DIR             102
#define AL_DIR_MASK             103
#define AL_READ_ARCHIVE         104
#define AL_APPEND               105
#define AL_INPUT_FILES          106
#define AL_DEBUG                107
#define AL_GOTO_INPUT           108
#define AL_GOTO_OUTPUT          109
#define AL_ABOUT                110
#define AL_EXIT                 111
#define AL_ARCHIVE_NAME         112
#define AL_ABORT                113
#define AL_PROGRESS_TEXT        114
#define IDC_STATIC               -1
