/*= Archive Library v2.12 ================================================
 |  Copyright (c) 1994-1997, Greenleaf Software, Inc.
 |  All Rights Reserved.
 |
 +- Description ----------------------------------------------------------
 |  Header file.
 |
 +========================================================================*/

#define AL_PROGRESS_BAR                 103
#define AL_INPUT_LIST                   104
#define AL_OUTPUT                       105
#define AL_APPEND                       106
#define AL_READ_INPUT                   107
#define AL_COPY                         108
#define AL_OUTPUT_LIST                  109
#define AL_DEBUG                        110
#define AL_READ_OUTPUT                  111
#define AL_GOTO_INPUT                   112
#define AL_GOTO_OUTPUT                  113
#define AL_ABOUT                        114
#define AL_EXIT                         115
#define AL_INPUT                        102
#define AL_ABORT                        101
#define AL_PROGRESS_TEXT                100
#define IDC_STATIC                      -1
