/*= Archive Library v2.12 ================================================
 |  Copyright (c) 1994-1997, Greenleaf Software, Inc.
 |  All Rights Reserved.
 |
 +- Description ----------------------------------------------------------
 |  Header file.
 |
 +========================================================================*/

#define AL_GOTO_INPUT               107
#define AL_ABOUT                    105
#define AL_EXIT                     106
#define AL_PROGRESS_TEXT            100
#define AL_PROGRESS_BAR             108
#define AL_CYCLE                    102
#define AL_INPUT_LIST               104
#define AL_ABORT                    101
#define IDC_STATIC                  -1
