/*= Archive Library v2.12 ================================================
 |  Copyright (c) 1994-1997, Greenleaf Software, Inc.
 |  All Rights Reserved.
 |
 +- Description ----------------------------------------------------------
 |  Header file.
 |
 +========================================================================*/

#define AL_CYCLE	            102
#define AL_FILES	            101
#define AL_PROGRESS_TEXT	    105
#define AL_PROGRESS_NUMBER	  106
#define AL_MAIN_DIALOG       100
#define AL_ABORT             103
#define AL_EXIT              104
#define AL_ABOUT             107
#define AL_ABOUT_TEXT	       201
#define AL_ICON	             300
#define AL_ABOUT_DIALOG	     200
#define AL_TEXT	             205
