/*= Archive Library v2.12 ================================================
 |  Copyright (c) 1994-1997, Greenleaf Software, Inc.
 |  All Rights Reserved.
 |
 +- Description ----------------------------------------------------------
 |  Header file.
 |
 +========================================================================*/

#define AL_DELETE_BAD_PTR	  107
#define AL_UNDERSHOOT	      106
#define AL_WRITE_PAST_END	  104
#define AL_DESTROY_TWICE	   102
#define AL_ABOUT	           105
#define AL_FILES	           101
#define AL_MAIN_DIALOG      100
#define AL_EXIT	            103
#define AL_ABOUT_TEXT	      201
#define AL_ICON	            300
#define AL_ABOUT_DIALOG	    200
#define AL_TEXT	            205
