/*= Archive Library v2.12 ================================================
 |  Copyright (c) 1994-1997, Greenleaf Software, Inc.
 |  All Rights Reserved.
 |
 +- Description ----------------------------------------------------------
 |  Header file.
 |
 +========================================================================*/

#define AL_ABOUT                        100
#define AL_DESTROY_TWICE                101
#define AL_EXIT                         102
#define AL_WRITE_PAST_END               103
#define AL_DELETE_BAD_POINTER           104
#define AL_EXERCISE                     105
#define AL_UNDERSHOOT                   106
#define IDC_STATIC                       -1
