/*= Archive Library v2.12 ================================================
 |  Copyright (c) 1994-1997, Greenleaf Software, Inc.
 |  All Rights Reserved.
 |
 +- Description ----------------------------------------------------------
 |  Header file.
 |
 +========================================================================*/

#define AL_INPUT_FILES                106
#define AL_CREATE_WIN_MEMORY_OBJECT	  115
#define AL_CREATE_HUGE_MEMORY_OBJECT	 114
#define AL_EXIT                       111
#define AL_OPEN_DISK_FILE             109
#define AL_FILE_STATUS_DETAIL         113
#define AL_FILE_STATUS_STRING         112
#define AL_FILE_TYPE                  110
#define AL_FILE_NAME                  105
#define AL_CREATE_MEMORY_OBJECT       108
#define IDC_STATIC                     -1
