/*= Archive Library v2.12 ================================================
 |  Copyright (c) 1994-1997, Greenleaf Software, Inc.
 |  All Rights Reserved.
 |
 +- Description ----------------------------------------------------------
 |  Header file.
 |
 +========================================================================*/

#define AL_RENAME                107
#define AL_OLD_NAME              109
#define AL_STATUS                110
#define AL_SEEK                  112
#define AL_NEW_NAME              105
#define AL_FILE_NAME             108
#define AL_RENAME_TO_BACKUP      116
#define AL_UNRENAME              115
#define AL_INPUT_FILES           106
#define AL_GOTO_INPUT            108
#define AL_GOTO_OUTPUT           109
#define AL_ABOUT                 110
#define AL_EXIT                  111
#define IDC_STATIC               -1
