/*= Archive Library v2.12 ================================================
 |  Copyright (c) 1994-1997, Greenleaf Software, Inc.
 |  All Rights Reserved.
 |
 +- Description ----------------------------------------------------------
 |  Header file.
 |
 +========================================================================*/

#define IDC_STATIC	              113
#define AL_PROGRESS_BAR	         107
#define AL_PROGRESS_TEXT	        112
#define AL_ENGINE_TYPE_STRING	   108
#define AL_ENGINE_TYPE_INT	      109
#define AL_ENGINE_STATUS_DETAIL	 111
#define AL_ENGINE_STATUS_INT	    110
#define AL_COMPRESS	             106
#define AL_GREENLEAF	            133
#define AL_PK	                   131
#define AL_COPY	                 132
#define AL_RAW_COMPRESSION	      120
#define AL_COMPRESSED_OBJECT	    121
#define AL_ARCHIVE	              122
#define AL_DIRECTORY	            101
#define AL_WILDSPEC	             102
#define AL_READ_DIR	             104
#define AL_ABOUT	                105
#define AL_MAIN_DIALOG           100
#define AL_EXIT	                 103
#define AL_ABOUT_TEXT	           201
#define AL_ICON	                 300
#define AL_ABOUT_DIALOG	         200
#define AL_TEXT	                 205
