/*= Archive Library v2.12 ================================================
 |  Copyright (c) 1994-1997, Greenleaf Software, Inc.
 |  All Rights Reserved.
 |
 +- Description ----------------------------------------------------------
 |  Header file.
 |
 +========================================================================*/

#define IDC_STATIC               -1
#define AL_READ_DIR              102
#define AL_DIR_MASK              103
#define AL_RAW_COMPRESS          104
#define AL_COMPRESS              105
#define AL_INPUT_FILES           106
#define AL_COMPRESSED_OBJECT     107
#define AL_ARCHIVE               108
#define IDC_GROUPBOX1            109
#define AL_ABOUT                 110
#define AL_EXIT                  111
#define AL_PROGRESS_BAR          112
#define AL_COPY_ENGINE           113
#define AL_GREENLEAF_ENGINE      114
#define AL_DEFLATE_ENGINE        115
#define IDC_GROUPBOX2            116
#define AL_ENGINE_TYPE_STRING    117
#define AL_ENGINE_STATUS_INT     118
#define AL_ENGINE_STATUS_DETAIL  119
#define AL_ENGINE_TYPE_INT       120
