/*= Archive Library v2.12 ================================================
 |  Copyright (c) 1994-1997, Greenleaf Software, Inc.
 |  All Rights Reserved.
 |
 +- Description ----------------------------------------------------------
 |  Header file.
 |
 +========================================================================*/

#define IDC_STATIC	               113
#define AL_ARCHIVE_NAME	          106
#define AL_ARCHIVE_VERSION	       107
#define AL_ARCHIVE_STATUS_CODE	   108
#define AL_ARCHIVE_STATUS_STRING	 109
#define AL_ARCHIVE_STATUS_DETAIL 	110
#define AL_FIRST_DUPLICATE_ENTRY 	111
#define AL_READ_DIR	              112
#define AL_DIR_MASK	              102
#define AL_CONTENTS	              104
#define AL_DIRECTORY	             101
#define AL_ABOUT	                 105
#define AL_MAIN_DIALOG            100
#define AL_EXIT	                  103
#define AL_ABOUT_TEXT	            201
#define AL_ICON	                  300
#define AL_ABOUT_DIALOG	          200
#define AL_TEXT	                  205
