/*= Archive Library v2.12 ================================================
 |  Copyright (c) 1994-1997, Greenleaf Software, Inc.
 |  All Rights Reserved.
 |
 +- Description ----------------------------------------------------------
 |  Header file.
 |
 +========================================================================*/

#define AL_ARCHIVE_NAME          105
#define AL_ARCHIVE_LISTING       107
#define AL_ARCHIVE_VERSION       109
#define AL_ARCHIVE_STATUS_STRING 112
#define AL_ARCHIVE_STATUS_DETAIL 113
#define AL_DUPLICATE_ENTRY_NAME  114
#define AL_ARCHIVE_STATUS_CODE   110
#define AL_DIR_MASK              108
#define AL_INPUT_FILES           106
#define AL_GOTO_INPUT            108
#define AL_GOTO_OUTPUT           109
#define AL_ABOUT                 110
#define AL_EXIT                  111
#define IDC_STATIC               -1
