/*= Archive Library v2.12 ================================================
 |  Copyright (c) 1994-1997, Greenleaf Software, Inc.
 |  All Rights Reserved.
 |
 +- Description ----------------------------------------------------------
 |  Header file.
 |
 +========================================================================*/

#define IDC_STATIC	           108
#define AL_CREATE_LIST	       103
#define AL_DELETE_LIST	       104
#define AL_DELETE_DUPLICATES	 105
#define AL_DIR_MASK	          102
#define AL_DIRECTORY	         101
#define AL_ABOUT	             106
#define AL_MAIN_DIALOG        100
#define AL_EXIT	              107
#define AL_ABOUT_TEXT	        201
#define AL_ICON	              300
#define AL_ABOUT_DIALOG	      200
