/*= Archive Library v2.12 ================================================
 |  Copyright (c) 1994-1997, Greenleaf Software, Inc.
 |  All Rights Reserved.
 |
 +- Description ----------------------------------------------------------
 |  Header file.
 |
 +========================================================================*/

#define AL_DIR_MASK             103
#define AL_DELETE_LIST          104
#define AL_DELETE_DUPLICATES    105
#define AL_CREATE_LIST          102
#define AL_INPUT_FILES          106
#define AL_GOTO_INPUT           108
#define AL_GOTO_OUTPUT          109
#define AL_ABOUT                110
#define AL_EXIT                 111
#define IDC_STATIC              -1
