/*= Archive Library v2.12 ================================================
 |  Copyright (c) 1994-1997, Greenleaf Software, Inc.
 |  All Rights Reserved.
 |
 +- Description ----------------------------------------------------------
 |  Header file.
 |
 +========================================================================*/

#define AL_CREATE               106
#define AL_DELETE               107
#define IDC_PUSHBUTTON1         108
#define AL_OLD_NAME             109
#define AL_GOOD_TAG             110
#define AL_SAFE_OLD_NAME        112
#define AL_RENAME               108
#define AL_NAME                 105
#define AL_ABOUT                110
#define AL_EXIT                 111
#define IDC_STATIC               -1
