/*= Archive Library v2.12 ================================================
 |  Copyright (c) 1994-1997, Greenleaf Software, Inc.
 |  All Rights Reserved.
 |
 +- Description ----------------------------------------------------------
 |  Header file.
 |
 +========================================================================*/

#define IDC_STATIC	            108
#define AL_FILES	              101
#define AL_FILE_NAME	          102
#define AL_UNIX_TIME_STAMP	    103
#define AL_DATE_AND_TIME	      104
#define AL_YEARS_SINCE_1970	   106
#define AL_ABOUT	              105
#define AL_MAIN_DIALOG         100
#define AL_EXIT	               107
#define AL_ABOUT_TEXT	         201
#define AL_ICON	               300
#define AL_ABOUT_DIALOG	       200
