/*= Archive Library v2.12 ================================================
 |  Copyright (c) 1994-1997, Greenleaf Software, Inc.
 |  All Rights Reserved.
 |
 +- Description ----------------------------------------------------------
 |  Header file.
 |
 +========================================================================*/

#define AL_YEARS                108
#define AL_DATE_AND_TIME        107
#define AL_TIME_STAMP           104
#define AL_FILE_NAME            105
#define AL_INPUT_FILES          106
#define AL_GOTO_INPUT           108
#define AL_GOTO_OUTPUT          109
#define AL_ABOUT                110
#define AL_EXIT                 111
#define IDC_STATIC              -1
