/*= Archive Library v2.12 ================================================
 |  Copyright (c) 1994-1997, Greenleaf Software, Inc.
 |  All Rights Reserved.
 |
 +- Description ----------------------------------------------------------
 |  Header file.
 |
 +========================================================================*/

#define AL_ABORT                        100
#define AL_PROCESS                      102
#define AL_PROGRESS_TEXT                101
#define AL_PROGRESS_NUMBER              103
#define AL_INPUT_FILES                  104
#define AL_ABOUT                        105
#define AL_EXIT                         106
#define AL_FILE_NAME                    107
#define IDC_STATIC                       -1
