/*= Archive Library v2.12 ================================================
 |  Copyright (c) 1994-1997, Greenleaf Software, Inc.
 |  All Rights Reserved.
 |
 +- Description ----------------------------------------------------------
 |  Header file.
 |
 +========================================================================*/

#define IDC_STATIC	          114
#define AL_TOTAL_INPUT	      106
#define AL_COMPRESS_ONLY	    113
#define AL_FILE	             110
#define AL_BYTE_COUNT	       111
#define AL_RESULTS	          112
#define AL_TOTAL_COMPRESSED	 107
#define AL_RATIO	            109
#define AL_TOTAL_TIME	       108
#define AL_COMPRESS	         104
#define AL_ABORT	            105
#define AL_INPUT_FILES	      101
#define AL_INPUT_TOTAL	      106
#define AL_ABOUT	            102
#define AL_MAIN_DIALOG       100
#define AL_EXIT	             103
#define AL_ABOUT_TEXT	       201
#define AL_ICON	             300
#define AL_ABOUT_DIALOG	     200
