/*= Archive Library v2.12 ================================================
 |  Copyright (c) 1994-1997, Greenleaf Software, Inc.
 |  All Rights Reserved.
 |
 +- Description ----------------------------------------------------------
 |  Header file.
 |
 +========================================================================*/

#define AL_ABORT                        100
#define AL_PROGRESS_TEXT                101
#define AL_COMPRESS_GREENLEAF           102
#define AL_PROGRESS_NUMBER              103
#define AL_INPUT_FILES                  104
#define AL_ABOUT                        105
#define AL_EXIT                         106
#define AL_DATA	                        107
#define AL_TOTAL_INPUT	                 108
#define AL_TOTAL_COMPRESSED	            109
#define AL_RATIO	                       110
#define AL_TIME	                        111
#define AL_RUDE	                        112
#define AL_COMPRESS_ONLY	               113
#define AL_HELP	                        114
#define AL_COMPRESS_ZIP                 115
#define IDC_STATIC                       -1
