//  Help Contexts...


#ifdef USE_SETUP_WINDOW
const USHORT BAUD_RATE                        = 0x0004;
const USHORT BAUD_300                         = 0x0005;
const USHORT BAUD_1200                        = 0x0006;
const USHORT BAUD_2400                        = 0x0007;
const USHORT BAUD_9600                        = 0x0008;
const USHORT BAUD_19200                       = 0x0009;
const USHORT FIELD_36                         = 0x0024;
const USHORT FULL_DUPLEX                      = 0x0025;
const USHORT XON_XOFF                         = 0x0026;
const USHORT SCROLL                           = 0x0027;
const USHORT FIELD_31                         = 0x001F;
const USHORT DISPLAY_BAUD                     = 0x0029;
const USHORT DISPLAY_FULL_DUPLEX              = 0x0021;
const USHORT DISPLAY_XON_XOFF                 = 0x0022;
const USHORT DISPLAY_SCROLL                   = 0x0023;
const USHORT FIELD_40                         = 0x0028;
#endif // USE_SETUP_WINDOW

