

#ifdef USE_TEST_WINDOW
const USHORT FIELD_50                         = 0x0032;
const USHORT FIELD_51                         = 0x0033;
const USHORT FIELD_52                         = 0x0034;
const USHORT FIELD_53                         = 0x0035;
const USHORT FIELD_54                         = 0x0036;
const USHORT FIELD_55                         = 0x0037;
const USHORT FIELD_56                         = 0x0038;
const USHORT FIELD_57                         = 0x0039;
const USHORT FIELD_58                         = 0x003A;
const USHORT FIELD_59                         = 0x003B;
#endif // USE_TEST_WINDOW

