# FREESTOR example makefile

#    nmake -f ibm.mak os2	(makes all the OS/2 freestore examples)

# ----- Usage --------------------------------------------------------------
usage:
	@echo ...........
	@echo ...........
	@echo (OS/2 environment does not support this example)
	@echo ...........
	@echo ...........

# ----- Clean ---------------------------------------------------------------
clean:
	z_clean.cmd

