//  Help Contexts...


#ifdef USE_WINDOW_DICTIONARY
const USHORT DCT_INPUT                        = 0x0004;
const USHORT DCT_DEFINITION                   = 0x0005;
const USHORT DCT_ANTONYM                      = 0x0006;
const USHORT DCT_SYNONYM                      = 0x0007;
const USHORT FIELD_0                          = 0x0001;
const USHORT DCT_LOOKUP_BUTTON                = 0x000A;
const USHORT DCT_SAVE_BUTTON                  = 0x000B;
const USHORT DCT_DELETE_BUTTON                = 0x000C;
const USHORT FIELD_25                         = 0x0003;
const USHORT FIELD_26                         = 0x0008;
const USHORT FIELD_27                         = 0x0009;
#endif // USE_WINDOW_DICTIONARY

