# ----- Usage --------------------------------------------------------------
usage:
	@echo ...........
	@echo ...........
	@echo To generate the Zinc demonstration for Borland C++ type:
	@echo make -fborland.mak dos
	@echo make -fborland.mak dos16
	@echo make -fborland.mak dosvrm
	@echo make -fborland.mak dosrtl
	@echo make -fborland.mak os2
	@echo make -fborland.mak pen
	@echo make -fborland.mak windows
	@echo make -fborland.mak winnt
	@echo ...........
	@echo To make the Zinc demonstration for IBM C++ type:
	@echo nmake -f ibm.mak os2
	@echo ...........
	@echo To generate the Zinc demonstration for Microsoft C++ type:
	@echo nmake -fmicrosft.mak dos
	@echo nmake -fmicrosft.mak dos16
	@echo nmake -fmicrosft.mak dosrtl
	@echo (Microsoft does not support OS/2)
	@echo nmake -fmicrosft.mak pen
	@echo nmake -fmicrosft.mak windows
	@echo nmake -f mscwnt.mak winnt
	@echo ...........
	@echo To generate the Zinc demonstration for Watcom C++ type:
	@echo wmake -f watcom.mak dos32
	@echo wmake -f watcom.mak windows
	@echo wmake -f watcom.mak os2
	@echo wmake -f watcom.mak dvx
	@echo ...........
	@echo To generate the Zinc demonstration for Zortech C++ type:
	@echo make -fzortech.mak dos
	@echo make -fzortech.mak dos16
	@echo make -fzortech.mak dos32
	@echo make -fzortech.mak os2
	@echo make -fzortech.mak pen
	@echo make -fzortech.mak windows
	@echo ...........
	@echo ...........
