//  Help Contexts...
const UI_HELP_CONTEXT HELP_GENERAL                     = 0x0001; // Help


#ifdef USE_SPA_WINDOW
const USHORT FIELD_32                         = 0x0020;
const USHORT FIELD_39                         = 0x0027;
const USHORT FIELD_50                         = 0x0032;
const USHORT FIELD_51                         = 0x0033;
const USHORT FIELD_16                         = 0x0010;
const USHORT FIELD_58                         = 0x003A;
const USHORT FIELD_33                         = 0x0021;
const USHORT FIELD_49                         = 0x0031;
const USHORT FIELD_52                         = 0x0034;
const USHORT FIELD_54                         = 0x0036;
const USHORT FIELD_66                         = 0x0042;
const USHORT FIELD_118                        = 0x0076;
const USHORT FIELD_119                        = 0x0077;
#endif // USE_SPA_WINDOW

#ifdef USE_US_WINDOW
const USHORT FIELD_32                         = 0x0020;
const USHORT FIELD_39                         = 0x0027;
const USHORT FIELD_50                         = 0x0032;
const USHORT FIELD_51                         = 0x0033;
const USHORT FIELD_16                         = 0x0010;
const USHORT FIELD_58                         = 0x003A;
const USHORT FIELD_33                         = 0x0021;
const USHORT FIELD_49                         = 0x0031;
const USHORT FIELD_52                         = 0x0034;
const USHORT FIELD_54                         = 0x0036;
const USHORT FIELD_66                         = 0x0042;
const USHORT FIELD_94                         = 0x005E;
const USHORT FIELD_95                         = 0x005F;
#endif // USE_US_WINDOW

#ifdef USE_GER_WINDOW
const USHORT FIELD_32                         = 0x0020;
const USHORT FIELD_39                         = 0x0027;
const USHORT FIELD_50                         = 0x0032;
const USHORT FIELD_51                         = 0x0033;
const USHORT FIELD_16                         = 0x0010;
const USHORT FIELD_58                         = 0x003A;
const USHORT FIELD_33                         = 0x0021;
const USHORT FIELD_49                         = 0x0031;
const USHORT FIELD_52                         = 0x0034;
const USHORT FIELD_54                         = 0x0036;
const USHORT FIELD_66                         = 0x0042;
const USHORT FIELD_126                        = 0x007E;
const USHORT FIELD_127                        = 0x007F;
#endif // USE_GER_WINDOW

