;
; Configuraci¢n [09/02/2001 11:38]
;
; Utilice SETUP para producir ST.CFG
;

;
; [ Sistema ]
;
COUNTRY=Colombia
CURRENCY=$
CITY=Medellín
COMPANY=TELECOM
ID=
OPERATOR_NAME=TELECOM
DEALER=0
TAX_NAME=IVA
TAX_PERCENT=16.00
CLUSTERS=2
SS_ID=0
SS_TIME=0
P_PORT=lpt
P_OPERATION=automatica
P_FORM=80 col. doble recibo
P_FOOTER1=
P_FOOTER2=
CASH=prn
LPT=1
DOUBLE_PRN=0
COM=1 2400 none 8 1
M_ROUND=0.05
MCARDS=5000.0,10000.0,15000.0,20000.0
TLX_BASE=566.40
INTER_TLX_BASE=0.00
USA=Estados Unidos
;
; [ Aplicacion ]
;
MANUAL_ANSWER=0
MIN_NAL=1
MIN_INTER=1
MIN_BORDER=1
MIN_USA=1
MIN_CELLULAR=1
CEIL_NAL=0.00
CEIL_INTER=1.00
CEIL_BORDER=0.00
CEIL_USA=1.00
CEIL_CELLULAR=1.00
N_RECEIPT=23080
TURN_DAY=9
TURN_NUMBER=1
N_DIAL_ERR=0
N_COM_ERR=0
MAX_COM_ERR=4
MAX_DIAL_ERR=4
DEFAULT_TARIFFS=A1(0),A2(0),A3(0),A4(0),A5(0),A6(0),A7(0),A8(0),A9(0)
APPLY_DDN_SCHEDULE=0
APPLY_DDI_SCHEDULE=1
GENERATE_PREPAID_RECEIPT=1
DOUBLE_PREPAID_RECEIPT=0
CACHE_SIZE=1024
CHECK_DUPS=0
MULTIPLE_PREPAID_CALLS=1
CALL_ACTUAL_COST=1
NO_SOUND_WHILE_SPY=1
ACTIVATE_RELAY=1
RELAY_NUMBER=1
VIEW_DECIMALS=0
CORRECTION_TIME=0
HEADER_LINE1=Recibo de pago de servicios públicos
HEADER_LINE2=
HEADER_LINE3=
HEADER_LINE4=Somos agente retenedor del
HEADER_PRINT_TAXNAME=1
HEADER_PRINT_RECNO=0
;
; [ Telefonia ]
;
T_ON_HOOK=150
T_INTER_RING=2000
T_OFF_HOOK=300
T_BREAK=30
T_MAKE=20
T_MAKE_MARGIN=80
T_INTERDIG=200
T_DTMF_FLAG=40
T_DTMF_INTERDIG=40
T_ANSWER=38000
T_TALK=3000
T_BIAS=150
T_DIAL=30000
T_COM=39000
T_STORE=550
T_LOCK=800
SIGNAL=inversion
;
; [ Marcacion ]
;
ACCESS_LEVELS=3
SPECIAL_ACCESS=1
ACCESS=0
OPERATOR_ACCESS=9
CELLULAR_ACCESS=3
CELLULAR_OPERATOR_ACCESS=3
EDA_ACCESS=8
BORDER_ACCESS=9
INTER_ACCESS=0
INTER_DIGITS=14
BORDER_DIGITS=14
CELLULAR_DIGITS=10
NAL_DIGITS=10
LOCAL_DIGITS=7
SPECIAL_DIGITS=3
NAL_DIGITS_MARGIN=1
LOCAL_DIGITS_MARGIN=1
INTER_DIGITS_MARGIN=4
INTER_DIGITS_NOT_INCLUDED=10
NAL_DIGITS_NOT_INCLUDED=9
LOCAL_DIGITS_NOT_INCLUDED=6
;
; [ Extensiones ]
;
E_APPLY_DDN_SCHEDULE=1
E_APPLY_DDI_SCHEDULE=1
E_DISCOUNT=0.00
E_INSTALL_COST=0.00
E_LINE_COST=0.00
E_MIN_AVAILABLE=1000.00
E_SHOW_PHONE=0
E_FIRST_EXT=0
E_N_RECEIPT=0
E_MIN_NAL=3
E_MIN_INTER=1
E_MIN_USA=1
E_MIN_BORDER=1
E_MIN_CELLULAR=1
E_CEIL_NAL=0.00
E_CEIL_INTER=1.00
E_CEIL_USA=0.00
E_CEIL_BORDER=0.00
E_CEIL_CELLULAR=1.00
E_APPLY_ROUND=1
;
; [ Valores Cr¡ticos ]
;
CHECK_PAUSE_KEY=1
IGNORE_EXTRA_DIGITS=0
EXCLUSIVE_SPY=1
IGNORE_PRE_ANSWER=0
DETECT_INCOME=0
EXIST_FALSE_ONE=0
;
; [ Modem ]
;
MODEM_COM=1
MODEM_BASE=760
MODEM_IRQ=3
MODEM_BAUDS=2400
MODEM_DIAL=9
MODEM_SPEAKER=1
MODEM_DELAY=1000
MODEM_RECEIVESENDDELAY=110
MODEM_ACKTIME=60
MODEM_MAXTIME=40000
MODEM_PHONE=3415600
;
; [ Display ]
;
DISPLAY_ENABLE=0
DISPLAY_COM=1
DISPLAY_BAUDS=9600
DISPLAY_DEFAULT_MESSAGE=SmartTar 2.22
