#ifdef USE_HELLO_WORLD_WINDOW
#endif // USE_HELLO_WORLD_WINDOW

#ifdef USE_WORLD_INFORMATION_WINDOW
#endif // USE_WORLD_INFORMATION_WINDOW

#ifdef USE_HELP_CONTEXTS
const UI_HELP_CONTEXT HELP_GENERAL                     = 0x0001; // General Help
const UI_HELP_CONTEXT HELP_HELLO_WORLD                 = 0x0002; // Hello World Help
const UI_HELP_CONTEXT HELP_WORLD_INFORMATION           = 0x0003; // World Information Help
#endif // USE_HELP_CONTEXTS

