#
#  EXAMPLES Makefile
#
#  The symbol SOURCE must be defined to the source filename (without
#  extension) that you want to compile.  For example, to compile
#  EXAMP001.CPP, issue the following command:
#
#    make -DSOURCE=examp001
#
#  One of the following symbols may be defined to build an app in a
#  target other than real mode (the default).
#
#     DOS32  -  build a 32 bit DPMI app
#
#
#  The following additional symbols may also be defined:
#
#     DEBUG   -  include debugging information in the app
#

.AUTODEPEND

!if !$d( SOURCE )
!error You must define SOURCE= to the file you wish to compile.
!endif

!if !$d(BCROOT)
BCROOT = $(MAKEDIR)\..
!endif

LIBPATH = $(BCROOT)\LIB;..\LIB       # is in the same place as the compiler
INCPATH = $(BCROOT)\INCLUDE;..\INCLUDE;

!ifdef DEBUG                         # set appropriate flags for debugging
CCDEBUGFLAG = -v
LINKDEBUGFLAG = /v
DEBUGSUFFIX = d
!endif

#
# default options produce a real mode application
#

CFGFILE    = $(SOURCE).CFG
CC         = bcc +$(CFGFILE)
TLINK      = tlink
STARTUP    = c0l.obj
USERLIBS   = cpl30.lib
STDLIBS    = emu.lib mathl.lib cl.lib
CCFLAGS    = -ml $(CCDEBUGFLAG)
LINKFLAGS  = $(LINKDEBUGFLAG)
OBJDIR     = objs16$(DEBUGSUFFIX)

#
# 32 bit protected mode application options
#

!ifdef DOS32
CFGFILE    = $(SOURCE).C32
CC         = bcc32 +$(CFGFILE)
TLINK      = tlink32
STARTUP    = c0x32.obj
USERLIBS   = cpfx32.lib
STDLIBS    = dpmi32.lib cw32.lib
CCFLAGS    = -WX $(CCDEBUGFLAG)
LINKFLAGS  = /Tpe/ax $(LINKDEBUGFLAG)
OBJDIR     = objs32$(DEBUGSUFFIX)
!endif

#
# implicit rule takes care of compiling all C++ files
#

.cpp.obj:
  $(CC) $(CCFLAGS) -c -n$(OBJDIR) {$< }


#
# link the exe
#

$(SOURCE).exe: dirs $(CFGFILE) $(OBJDIR)\$(SOURCE).obj
  $(TLINK) @&&|
$(LINKFLAGS)/L$(LIBPATH) +      # linker options
$(STARTUP) +                    # startup code
$(OBJDIR)\$(SOURCE).obj         # user object files
$(SOURCE)                       # exe name
$(SOURCE)                       # mapfile
$(USERLIBS) +                   # overlayable libraries
$(STDLIBS)                      # non-overlayable libraries
|

#
# the following rule ensures that the appropriate OBJS
# directory exists.
#

dirs:
  IF NOT EXIST $(OBJDIR) MD $(OBJDIR)

#
# source file depends on the cfg file, which is created
# whenever the makefile is modified
#

$(OBJDIR)\$(SOURCE).obj: $(CFGFILE) $(SOURCE).cpp

#
# create a new configuration file whenever the makefile
# has been modified
#

$(CFGFILE): makefile
  copy &&|
-w
-x-
-I$(INCPATH)
-L$(LIBPATH)
| $(CFGFILE)